<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "armconstructions"
 *
 * Auto generated by Extension Builder 2017-02-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'ARM Constructions',
	'description' => 'Manage accounts of a construction business',
	'category' => 'plugin',
	'author' => 'ARM Technologies',
	'author_email' => 'anisur.mullick@gmail.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.6',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);